# Generated by Django 4.2.7 on 2023-12-03 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospPatients',
            fields=[
                ('subject_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('gender', models.TextField(blank=True, null=True)),
                ('anchor_age', models.TextField(blank=True, null=True)),
                ('anchor_year', models.TextField(blank=True, null=True)),
                ('anchor_year_group', models.TextField(blank=True, null=True)),
                ('dod', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hosp_patients',
            },
        ),
        migrations.CreateModel(
            name='DoctorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(related_name='doctor_groups', to=settings.AUTH_USER_MODEL)),
                ('patients', models.ManyToManyField(related_name='doctor_groups', to='dashboard.hosppatients')),
            ],
        ),
    ]
