# Generated by Django 4.2.7 on 2023-12-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosppatients',
            options={'managed': False},
        ),
    ]
